# Generated by Django 4.1.1 on 2022-10-08 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("directory", "0002_register"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlightTask",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("create_at", models.DateTimeField(auto_now=True)),
                ("update_at", models.DateTimeField(auto_now_add=True)),
                ("task_date", models.DateField(verbose_name="Date")),
                (
                    "technology",
                    models.CharField(
                        choices=[("arrival", "Arrival"), ("departure", "Departure")],
                        default="",
                        max_length=15,
                        verbose_name="Tech",
                    ),
                ),
                (
                    "aircraft_type",
                    models.CharField(
                        default="", max_length=50, verbose_name="Aircraft"
                    ),
                ),
                (
                    "flight",
                    models.CharField(default="", max_length=6, verbose_name="Flight"),
                ),
                (
                    "sched_time",
                    models.TimeField(blank=True, null=True, verbose_name="SCTA"),
                ),
                (
                    "route",
                    models.CharField(default="", max_length=10, verbose_name="From"),
                ),
                ("payload", models.TextField(default="", verbose_name="Payload")),
                (
                    "description",
                    models.TextField(default="", verbose_name="Description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("completed", "Completed"),
                            ("inprogress", "InProgress"),
                            ("canceled", "Canceled"),
                            ("standBy", "StandBy"),
                        ],
                        default="draft",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                ("slug", models.SlugField(editable=False, unique=True)),
                ("is_return", models.BooleanField(default=False)),
                (
                    "airline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flight_airline",
                        to="directory.airline",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flight_register",
                        to="directory.register",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "FlightTask",
                "verbose_name_plural": "FlightTasks",
                "ordering": ("-status",),
            },
        ),
    ]
