# Generated by Django 4.1.1 on 2022-10-12 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight_schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flighttask',
            name='aircraft_type',
        ),
    ]
