# Generated by Django 4.1.1 on 2022-10-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_schedule', '0003_alter_flighttask_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flighttask',
            name='is_return',
        ),
        migrations.AlterField(
            model_name='flighttask',
            name='payload',
            field=models.CharField(default='', max_length=15, verbose_name='Payload'),
        ),
        migrations.AlterField(
            model_name='flighttask',
            name='sched_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Schedule time'),
        ),
    ]
