# Generated by Django 4.1.1 on 2022-10-09 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0002_register"),
    ]

    operations = [
        migrations.AddField(
            model_name="airline",
            name="logo",
            field=models.ImageField(
                blank=True,
                height_field=75,
                null=True,
                upload_to="media/airlines/logos/",
                verbose_name="Logo",
                width_field=75,
            ),
        ),
    ]
