# Generated by Django 4.1.1 on 2022-10-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0004_alter_airline_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airline",
            name="logo",
            field=models.ImageField(
                blank=True,
                default="media/airlines/logos/default_logo",
                null=True,
                upload_to="media/airlines/logos/",
                verbose_name="Logo",
            ),
        ),
    ]
