# Generated by Django 4.1.1 on 2022-10-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_alter_airline_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='co',
            field=models.CharField(default='', max_length=5, verbose_name='Company'),
        ),
    ]
