# Generated by Django 4.1.1 on 2022-10-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_alter_register_co'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata', models.CharField(default='', max_length=3, verbose_name='IATA')),
                ('icao', models.CharField(default='', max_length=4, verbose_name='ICAO')),
            ],
        ),
    ]
