# Generated by Django 4.1.1 on 2022-10-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata_code', models.CharField(default='', max_length=3, verbose_name='IATA')),
                ('icao_code', models.CharField(default='', max_length=4, verbose_name='ICAO')),
                ('rus_name', models.CharField(default='', max_length=7, verbose_name='Rus')),
                ('comment', models.CharField(default='', max_length=100, verbose_name='Comment eng')),
                ('comment_rus', models.CharField(default='', max_length=100, verbose_name='Comment rus')),
                ('public_name_eng', models.CharField(default='', max_length=155, verbose_name='Public name eng')),
                ('public_name_rus', models.CharField(default='', max_length=155, verbose_name='Public name rus')),
            ],
        ),
    ]
